//! The on-disk note store: a `.ynotes/` directory backed by a
//! content-addressed object store.
//!
//! Layout:
//!
//! ```text
//! .ynotes/
//!   HEAD                     format sentinel; its presence marks the root
//!   notes/<aa>/<rest>.json   one note per file, fanned out by id prefix
//!   index/by-path.json       union-mergeable JSONL: one {"target","id"} line per note
//! ```
//!
//! Two rules the rest of the engine relies on:
//!
//! 1. **Note files are immutable and content-addressed.** They are written to
//!    a temp file in the same directory and atomically renamed into place, so
//!    a crash never leaves a half-written note.
//! 2. **The index is a rebuildable cache, not the source of truth.** It can be
//!    regenerated by scanning `notes/`. A corrupt index must never cost a
//!    note, this is the storage face of the never-silently-dropped invariant.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use fs4::fs_std::FileExt;

use crate::error::{Error, Result};
use crate::note::Note;
use crate::path::{canonical_for_compare, to_forward_slash};

/// Directory name of the store, created at a project root.
const STORE_DIRNAME: &str = ".ynotes";

/// Contents of the `HEAD` sentinel; the integer is the store format version.
const HEAD_CONTENTS: &str = "ynotes 1\n";

/// Filename of the per-store advisory lock. Held exclusively across any
/// read-modify-write of the by-path index so two concurrent writers cannot
/// lose each other's entries.
const LOCK_FILENAME: &str = "lock";

/// One managed line in a store git-config file: the path/pattern it governs and
/// the exact line we write. We append a managed line only when no existing line
/// already targets its `pattern`, so a user who customised the driver for a
/// pattern keeps their version, while a store missing a managed line (e.g. one
/// created before the note-merge guard existed) gains it on the next
/// `init`/`reindex`. Existing lines are never modified or reordered.
struct ManagedLine {
    /// First whitespace-delimited token of the line: the path/pattern the
    /// attribute applies to. Any existing line starting with this token means
    /// the user has an opinion we must not override.
    pattern: &'static str,
    /// The exact line (no trailing newline) appended when `pattern` is absent.
    line: &'static str,
}

/// Managed `.ynotes/.gitattributes` lines. `merge=union` keeps the JSONL index
/// cache mergeable; `notes/** -merge` stops git running a *textual* three-way
/// merge on the content-addressed note files, without it, a concurrent
/// supersede (reanchor/update) or identical save across branches lets git's
/// rename detection inject conflict markers into note JSON, corrupting the
/// store. `union` and `-merge` are git built-ins, so this needs no per-clone
/// `.git/config`. Patterns are relative to `.ynotes/`.
const GITATTRIBUTES_MANAGED: &[ManagedLine] = &[
    ManagedLine {
        pattern: "index/by-path.json",
        line: "index/by-path.json merge=union",
    },
    ManagedLine {
        pattern: "notes/**",
        line: "notes/** -merge",
    },
];

/// Managed `.ynotes/.gitignore` lines: keep the local advisory lock out of
/// commits while the rest of the store is shared.
const GITIGNORE_MANAGED: &[ManagedLine] = &[ManagedLine {
    pattern: "lock",
    line: "lock",
}];

/// Environment variable that points directly at a `.ynotes` directory,
/// bypassing the upward walk (`GIT_DIR` semantics, needed by a future
/// long-lived server that has no meaningful current directory).
const ENV_DIR: &str = "YNOTES_DIR";

/// The reverse index: which note ids belong to each target path.
type IndexMap = std::collections::BTreeMap<String, Vec<String>>;

/// One on-disk index entry. The index is stored as JSONL, one of these per
/// line, so `git merge=union` keeps concurrent adds structurally valid (a
/// nested JSON object cannot be union-merged without risking invalid JSON).
#[derive(serde::Serialize, serde::Deserialize)]
struct IndexLine {
    target: String,
    id: String,
}

/// One JSON record discovered under `notes/`. The path is always retained;
/// `id` is absent only when the filename does not have the canonical
/// content-addressed shape.
struct RecordFile {
    id: Option<String>,
    path: PathBuf,
}

/// A record under `notes/` that could not be read or parsed as a [`Note`].
///
/// Surfaced by the read paths rather than dropped or made fatal: one corrupt
/// record must neither sink an otherwise healthy read nor hide behind it
/// (invariant #4). Mirrors [`ReindexReport::malformed`]'s posture, carried
/// through to the reads an agent actually queries.
#[derive(Debug, Clone)]
pub struct MalformedNote {
    /// The id encoded by the record path, when it has the canonical
    /// `notes/<aa>/<rest>.json` shape. An arbitrary malformed JSON file has no
    /// safe id to infer.
    pub id: Option<String>,
    /// The target path the index grouped it beneath, when the cache still has
    /// that pointer. An unindexed malformed record has no readable source from
    /// which to recover its target, so this is deliberately unknown.
    pub target: Option<String>,
    /// Store-relative path to the unreadable record. Always present, including
    /// when neither an id nor a target can be recovered.
    pub path: String,
    /// Why the record could not be read or parsed. Free-form, for display,
    /// not a stable key to branch on (the presence of an entry is the signal).
    pub error: String,
}

/// The outcome of reading the notes for a target (or the whole store): the
/// records that parsed cleanly, plus any that did not.
///
/// Replaces a bare `Vec<Note>` so a malformed record travels alongside the
/// healthy ones, skipped from `notes`, surfaced in `malformed`, never the
/// cause of a hard failure.
#[derive(Debug, Clone, Default)]
pub struct NoteScan {
    /// Records that parsed cleanly, in deterministic order.
    pub notes: Vec<Note>,
    /// Records under `notes/` that could not be read or parsed.
    pub malformed: Vec<MalformedNote>,
    /// Drift observed between the record files and the rebuildable index cache.
    /// Reads report this condition but never repair it.
    pub index: IndexHealth,
}

/// The outcome of resolving an id or hex prefix to a note via
/// [`Store::match_id_prefix`].
///
/// The three cases a by-id selection lands in, surfaced as data so each
/// front-end decides how to present them: the CLI turns [`IdMatch::Ambiguous`]
/// and [`IdMatch::None`] into usage errors, while a server might return them
/// structurally. Keeping them out of [`Error`] is what lets a resolve stay a
/// pure lookup, only a genuine store failure is an error.
///
/// The [`IdMatch::One`] variant carries a whole [`Note`] inline rather than a
/// `Box`, so the enum is as large as a note. That is deliberate: this is a
/// transient, single-value return (never held in bulk), and the shape is a
/// fixed cross-crate contract every front-end matches on, indirection would
/// buy nothing but a heap hop and an awkward `Box` at every call site.
#[allow(clippy::large_enum_variant)]
#[derive(Debug, Clone)]
pub enum IdMatch {
    /// Exactly one note matched the prefix.
    One(Note),
    /// More than one note matched; every candidate is carried (ascending id
    /// order, as [`Store::find_by_id_prefix`] returns) so the caller can list
    /// them.
    Ambiguous(Vec<Note>),
    /// No note matched the prefix.
    None,
}

/// A handle to an opened store, identified by its `.ynotes` directory.
#[derive(Debug, Clone)]
pub struct Store {
    root: PathBuf,
}

/// The outcome of a [`Store::reindex`] pass: what rebuilding `by-path.json`
/// from the note records on disk changed, relative to the index that was
/// there.
///
/// A healthy store reindexes to an empty report, nothing recovered, nothing
/// dangling, nothing malformed, because the index already agreed with
/// `notes/`. A non-empty `recovered`/`dangling` means the index had drifted
/// from the notes on disk and has now been reconciled to them (the notes are
/// the source of truth; the index is a cache).
#[derive(Debug, Clone)]
pub struct ReindexReport {
    /// Whether this was a preview; with `true` the on-disk index was left
    /// untouched.
    pub dry_run: bool,
    /// Note records read successfully while scanning `notes/`.
    pub scanned: usize,
    /// Distinct notes in the rebuilt index (its entry count).
    pub indexed: usize,
    /// Ids found on disk that the previous index did not list, pointers that
    /// were missing and have now been restored.
    pub recovered: Vec<String>,
    /// Ids the previous index listed that have no file behind them on disk,
    /// dangling pointers that have now been dropped.
    pub dangling: Vec<String>,
    /// Files under `notes/` that could not be read or parsed as a note.
    /// Skipped so one corrupt record cannot sink the rebuild, and surfaced
    /// here (and via `tracing::warn!`) rather than silently discarded, a
    /// readable note is never dropped, and an unreadable one is never hidden
    /// (invariant #4).
    pub malformed: Vec<PathBuf>,
}

/// The result of scanning `notes/` and diffing it against the index, shared by
/// [`Store::reindex`] and [`Store::health`]. Private: the two public callers
/// each project it into their own report ([`ReindexReport`]/[`StoreHealth`]).
struct ScanOutcome {
    /// The `target -> [id]` map rebuilt from the records on disk.
    rebuilt: IndexMap,
    /// Note records read successfully while scanning `notes/`.
    scanned: usize,
    /// Distinct notes found on disk (the rebuilt index's entry count).
    indexed: usize,
    /// Ids on disk the current index did not list (recoverable pointers).
    recovered: Vec<String>,
    /// Ids the current index listed with no file behind them (dangling).
    dangling: Vec<String>,
    /// Files under `notes/` that could not be read or parsed as a note.
    malformed: Vec<PathBuf>,
    /// Whether the baseline index was readable, absent, or malformed.
    index_status: IndexStatus,
}

/// A read-only health report on the store, produced by [`Store::health`] and
/// rendered by `ynotes doctor`. Empty across the board on a sound store.
#[derive(Debug, Clone)]
pub struct StoreHealth {
    /// Records under `notes/` that could not be read or parsed as a note,
    /// present but corrupt. Skipped by the read paths and surfaced here so a
    /// corrupt record is visible rather than silently dropped (invariant #4).
    pub malformed: Vec<PathBuf>,
    /// How far the index cache has drifted from the notes on disk.
    pub index: IndexHealth,
    /// Managed `.gitattributes` lines absent from `.ynotes/.gitattributes`. A
    /// non-empty list on a shared store means the merge guards are not in
    /// force (`init`/`reindex` re-add them).
    pub gitattributes_missing: Vec<String>,
}

/// What one [`Store::save_superseding`] did, and what was already there.
#[derive(Debug, Clone)]
pub struct SaveOutcome {
    /// `false` when an identical note already existed, `save` is idempotent
    /// (invariant #6), so a retry is not a second creation.
    pub created: bool,
    /// How many prior notes at the identical location this save retired.
    pub superseded: usize,
    /// Every *other* live note on the same file, earliest region first.
    ///
    /// The answer to "what does this file already say?", which is the question
    /// worth asking at exactly the moment a new note is being written. An empty
    /// list is the common and healthy case.
    pub neighbours: Vec<Note>,
}

/// How far the by-path index has drifted from the note records on disk. Both
/// zero on a sound store. Surfaced as counts (not id lists) because `doctor`'s
/// job is to flag the *condition*; `reindex` reports and repairs the specifics.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct IndexHealth {
    /// Whether the index cache was readable for this scan.
    pub status: IndexStatus,
    /// Ids present on disk but missing from the index, pointers a reindex
    /// would restore.
    pub recovered: usize,
    /// Index pointers with no file behind them at all, a reindex would drop
    /// them. A present-but-unreadable record is *not* counted here (it is
    /// reported under [`StoreHealth::malformed`]); this is strictly the
    /// missing-file case.
    pub dangling: usize,
}

/// Readability of the rebuildable by-path index cache.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum IndexStatus {
    /// The index file parsed successfully.
    #[default]
    Healthy,
    /// The index file was absent.
    Missing,
    /// The index file existed but did not parse or contained invalid ids.
    Malformed,
}

impl IndexHealth {
    /// Human-facing repair advisory for degraded cache state. `None` only when
    /// the index parsed and its identities agree with the record files.
    #[must_use]
    pub fn advisory(self) -> Option<String> {
        let condition = match self.status {
            IndexStatus::Missing => "index cache is missing".to_owned(),
            IndexStatus::Malformed => "index cache is malformed".to_owned(),
            IndexStatus::Healthy if self.recovered > 0 || self.dangling > 0 => format!(
                "index cache is out of sync ({} unindexed, {} dangling)",
                self.recovered, self.dangling
            ),
            IndexStatus::Healthy => return None,
        };
        Some(format!("{condition}; run `ynotes reindex` to repair it"))
    }
}

impl Store {
    /// Ensures a store exists under `workdir` (i.e. `workdir/.ynotes`).
    /// Idempotent: a pre-existing valid store is reopened, not refused,
    /// "already in the desired state" is success, not an error.
    ///
    /// A `.ynotes` directory that exists but lacks a `HEAD` sentinel is
    /// refused as [`Error::Invalid`], writing into someone else's directory
    /// of the same name would be unsafe.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if `.ynotes` exists but is not a ynotes
    /// store, or [`Error::Io`] if any directory or sentinel file cannot be
    /// written.
    pub fn init(workdir: &Path) -> Result<Self> {
        let root = workdir.join(STORE_DIRNAME);
        if root.join("HEAD").is_file() {
            let store = Self { root };
            // Re-running init is also the explicit repair path for a store
            // created before a managed git rule existed or checked out without
            // those files.
            store.write_git_config_files()?;
            return Ok(store);
        }
        if root.exists() {
            return Err(Error::Invalid(format!(
                "`{}` exists but is not a ynotes store (no HEAD)",
                root.display()
            )));
        }
        let store = Self { root };
        mkdir(&store.notes_dir())?;
        mkdir(&store.index_dir())?;
        write_file(&store.head_path(), HEAD_CONTENTS.as_bytes())?;
        store.write_index(&IndexMap::new())?;
        store.write_git_config_files()?;
        Ok(store)
    }

    /// Opens an existing store given its `.ynotes` directory directly,
    /// validating the `HEAD` sentinel. This is the seam a long-lived server
    /// (which has no meaningful current directory) uses.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if `root` is not a valid store.
    pub fn open(root: &Path) -> Result<Self> {
        if root.join("HEAD").is_file() {
            Ok(Self {
                root: root.to_path_buf(),
            })
        } else {
            Err(Error::Invalid(format!(
                "`{}` is not a ynotes store (no HEAD)",
                root.display()
            )))
        }
    }

    /// Locates the store by walking from `start` up to the filesystem root,
    /// returning the first ancestor containing a `.ynotes/HEAD`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::StoreNotFound`] if no store is found in any ancestor.
    pub fn discover_from(start: &Path) -> Result<Self> {
        let mut dir = start;
        loop {
            let candidate = dir.join(STORE_DIRNAME);
            if candidate.join("HEAD").is_file() {
                return Ok(Self { root: candidate });
            }
            match dir.parent() {
                Some(parent) => dir = parent,
                None => {
                    return Err(Error::StoreNotFound {
                        searched_from: start.to_path_buf(),
                    });
                }
            }
        }
    }

    /// Locates the store: `$YNOTES_DIR` if set (pointed directly at a
    /// `.ynotes` directory), otherwise the nearest ancestor of the current
    /// directory containing a `.ynotes/HEAD`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::StoreNotFound`] if no store is found, [`Error::Io`] if
    /// the current directory cannot be determined, or [`Error::Invalid`] if
    /// `$YNOTES_DIR` does not point at a valid store.
    pub fn discover() -> Result<Self> {
        if let Some(dir) = std::env::var_os(ENV_DIR) {
            return Self::open(&PathBuf::from(dir));
        }
        let start = std::env::current_dir().map_err(|source| Error::Io {
            path: PathBuf::from("."),
            source,
        })?;
        Self::discover_from(&start)
    }

    /// Discover the store from `start` upward; when none exists, create one at
    /// the enclosing git repository's root (`.git` directory *or* file, a
    /// worktree's `.git` is a file). Returns the store and whether this call
    /// created it. Used by CLI save; explicit-root MCP calls use
    /// [`Store::open_or_init_at_root`] instead.
    ///
    /// `$YNOTES_DIR`, when set (pointed directly at a `.ynotes` directory),
    /// wins outright, the same precedence as [`Store::discover`], so the
    /// write path cannot disagree with the read paths about which store is in
    /// force. The override is never a creation site: an explicit override
    /// names a store that must already exist, so pointing it at a non-store
    /// is refused rather than conjuring a store at an arbitrary location.
    ///
    /// # Errors
    ///
    /// [`Error::StoreNotFound`] when no store exists and no git root encloses
    /// `start` (an explicit `ynotes init` is the remedy), or
    /// [`Error::Invalid`] if `$YNOTES_DIR` does not point at a valid store;
    /// otherwise any [`Store::init`]/[`Store::discover_from`] failure.
    pub fn discover_or_init_from(start: &Path) -> Result<(Self, bool)> {
        if let Some(dir) = std::env::var_os(ENV_DIR) {
            return Ok((Self::open(&PathBuf::from(dir))?, false));
        }
        match Self::discover_from(start) {
            Ok(store) => Ok((store, false)),
            Err(Error::StoreNotFound { .. }) => {
                let Some(root) = find_git_root(start) else {
                    return Err(Error::StoreNotFound {
                        searched_from: start.to_path_buf(),
                    });
                };
                // `Store::init` is idempotent (it reopens a pre-existing valid
                // store), so the benign discover/init race, another process
                // creating the same root's store between the failed
                // `discover_from` and here, resolves to a reopen, not a
                // conflict. Report `true`: this call reached init for a store
                // discovery did not find.
                Ok((Self::init(&root)?, true))
            }
            Err(e) => Err(e),
        }
    }

    /// Open the store lying directly beneath `root`, with no upward search.
    ///
    /// The read primitive for a caller that already selected its repository
    /// explicitly. Selection must be exact: a repository that never adopted
    /// ynotes is a successful empty answer, never a fall-through to a parent
    /// workspace's store. Owning the store directory name here is what keeps a
    /// front-end from encoding the on-disk layout.
    ///
    /// `$YNOTES_DIR` is deliberately not consulted: it overrides *discovery*,
    /// and there is no discovery here. Honouring it would let one ambient
    /// variable silently redirect every explicitly addressed repository to a
    /// single store, which is exactly the confusion invariant #13 exists to
    /// prevent on the MCP path. Same reasoning in
    /// [`Store::open_or_init_at_root`].
    ///
    /// # Errors
    ///
    /// Any [`Store::open`] failure. A `.ynotes` that exists but lacks `HEAD`
    /// is corruption to surface, not an absence to report as "not adopted".
    pub fn open_at_root(root: &Path) -> Result<Option<Self>> {
        let store_root = root.join(STORE_DIRNAME);
        if store_root.exists() {
            Self::open(&store_root).map(Some)
        } else {
            Ok(None)
        }
    }

    /// Open the store beneath `root`, creating one there when absent, but only
    /// if `root` is itself a git repository root. Returns the store and whether
    /// this call created it.
    ///
    /// Unlike [`Store::discover_or_init_from`], this never searches ancestors.
    /// Restricting creation to the Git root prevents accidental nested stores
    /// that later reads at the repository root would miss.
    ///
    /// A store deliberately placed in a subdirectory stays reachable: explicit
    /// `ynotes init` may create one anywhere, and [`Store::open_at_root`] finds
    /// it. Only *automatic* creation is restricted to a repository root.
    ///
    /// `$YNOTES_DIR` is not consulted, for the reason given on
    /// [`Store::open_at_root`]; here it would be worse still, redirecting a
    /// *write*.
    ///
    /// # Errors
    ///
    /// [`Error::StoreNotFound`] when no store lies beneath `root` and `root` is
    /// not a repository root, an explicit `ynotes init` is the remedy.
    /// Otherwise any [`Store::open`] or [`Store::init`] failure.
    pub fn open_or_init_at_root(root: &Path) -> Result<(Self, bool)> {
        if let Some(store) = Self::open_at_root(root)? {
            return Ok((store, false));
        }
        // A worktree's `.git` is a file and a plain clone's is a directory, so
        // existence, not directoryness, is the test.
        if !root.join(".git").exists() {
            return Err(Error::StoreNotFound {
                searched_from: root.to_path_buf(),
            });
        }
        // `init` is idempotent, so the benign race with another process
        // creating the same store resolves to a reopen rather than a conflict.
        Ok((Self::init(root)?, true))
    }

    /// The `.ynotes` directory backing this store.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// The work tree the store sits in (the parent of `.ynotes`).
    ///
    /// # Errors
    ///
    /// [`Error::Invalid`] if `.ynotes` somehow has no parent (e.g. a store
    /// created at a filesystem root).
    pub fn workdir(&self) -> Result<&Path> {
        self.root
            .parent()
            .ok_or_else(|| Error::Invalid("store has no parent directory".to_owned()))
    }

    /// A note's target identity: `path` made relative to the work tree, with
    /// forward slashes. Save and query must agree on this string, so the
    /// derivation collapses anything two spellings of the same physical file
    /// might disagree on, `..` segments, `.` segments, and symlinked roots
    /// like macOS's `/tmp -> /private/tmp`, *before* `strip_prefix`. The
    /// alternative (`std::path::absolute` alone) is purely lexical and treats
    /// `sub/../sub/file.txt` and `sub/file.txt` as different keys, breaking
    /// the content-addressed id invariant (#6) for the same physical file.
    ///
    /// Does **not** require `path` to exist: for a missing input, only the
    /// deepest existing ancestor is canonicalised and the tail is appended
    /// lexically, so `query`/`delete`/`list` can still look up notes whose
    /// target file has since been removed.
    ///
    /// # Errors
    ///
    /// [`Error::OutsideStore`] if `path` resolves outside the work tree
    /// (a user input error the binary maps to exit `2`), or [`Error::Io`] if
    /// the work tree itself cannot be canonicalised.
    pub fn relativize(&self, path: &Path) -> Result<String> {
        let workdir = self.workdir()?;
        let canon_work = workdir.canonicalize().map_err(|source| Error::Io {
            path: workdir.to_path_buf(),
            source,
        })?;
        let canon_path = canonical_for_compare(path);
        match canon_path.strip_prefix(&canon_work) {
            Ok(rel) => Ok(to_forward_slash(rel)),
            Err(_) => Err(Error::OutsideStore {
                path: path.to_path_buf(),
                store_root: canon_work,
            }),
        }
    }

    /// Refuse a *symlink* whose canonical target lives outside this store's
    /// work tree, the write-path mirror of `reanchor`'s in-engine
    /// canonicalisation guard.
    ///
    /// The lexical [`Store::relativize`] catches a path *spelled* outside the
    /// work tree, but it deliberately works for files that do not yet exist and
    /// so cannot follow symlinks: a path whose name lives inside the store but
    /// whose symlink target points elsewhere therefore passes it. This closes
    /// that gap, and *only* that gap, by canonicalising both sides when the
    /// path is a symlink, so the resolved contents of an escaping link are never
    /// read into a note's selector bundle (which, on a committed `.ynotes`,
    /// would leak whatever the saver's filesystem put behind the link).
    ///
    /// Scope is deliberately narrow. A non-symlink path falls through here even
    /// if it sits outside the work tree, because [`Store::relativize`] is the
    /// authoritative outside-the-store check for ordinary paths, it produces a
    /// single, accurate [`Error::OutsideStore`] for every non-symlink case
    /// (absolute outside paths, devices like `/dev/null`, paths that do not
    /// exist yet). Blaming those on a symlink that is not there would be a
    /// misleading message.
    ///
    /// A no-op when `file` does not exist on disk (no metadata to read): the
    /// caller then fails further down with a clearer missing-file error.
    ///
    /// # Errors
    ///
    /// Returns [`Error::SymlinkEscape`] if `file` is a symlink resolving outside
    /// the work tree, or propagates [`Store::workdir`]'s [`Error::Invalid`] if
    /// the store has no work tree.
    pub fn reject_symlink_escape(&self, file: &Path) -> Result<()> {
        // `symlink_metadata`, not `metadata`: we want the link itself, not what
        // it points at. A missing file is silently ignored, the lexical check
        // and the subsequent read will produce the right diagnostic.
        let Ok(meta) = file.symlink_metadata() else {
            return Ok(());
        };
        if !meta.file_type().is_symlink() {
            return Ok(());
        }

        let workdir = self.workdir()?;
        let Ok(canon_file) = file.canonicalize() else {
            return Ok(());
        };
        let Ok(canon_work) = workdir.canonicalize() else {
            return Ok(());
        };
        if canon_file.strip_prefix(&canon_work).is_err() {
            return Err(Error::SymlinkEscape {
                path: file.to_path_buf(),
                workdir: canon_work,
                resolved: canon_file,
            });
        }
        Ok(())
    }

    /// Persists `note`, then indexes it under its target path.
    ///
    /// **Idempotent.** The id is content-addressed, so saving identical
    /// context again is a no-op: the existing record is left untouched.
    /// Returns `true` if this call created a new note, `false` if an
    /// identical one already existed, so an agent retrying a `save` tool
    /// call neither duplicates nor errors.
    ///
    /// **Race-safe.** "Already existed" is detected by an atomic
    /// rename-no-replace, not a check-then-write, so two concurrent saves of
    /// the same content cannot both report `created: true`. Field testing
    /// caught the older TOCTOU form reporting two creations for one record.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if the record or index cannot be written, or
    /// [`Error::Invalid`] if the existing index is unreadable.
    pub fn save(&self, note: &Note) -> Result<bool> {
        self.with_index_lock(|| {
            // Validate the cache before creating the immutable record. Without
            // this preflight, a refused write into a missing/malformed index can
            // still leave a new unindexed object behind.
            let mut index = self.read_index()?;
            self.repair_git_config_files();
            let path = self.note_path(&note.id);
            let bytes = serde_json::to_vec_pretty(note)
                .map_err(|e| Error::Invalid(format!("cannot serialise note `{}`: {e}", note.id)))?;
            if let Some(parent) = path.parent() {
                mkdir(parent)?;
            }
            let created = write_file_noclobber(&path, &bytes)?;
            let ids = index.entry(note.target.clone()).or_default();
            if !ids.contains(&note.id) {
                ids.push(note.id.clone());
            }
            self.write_index(&index)?;
            Ok(created)
        })
    }

    /// Saves `note`, then retires every prior note at the *same location* so
    /// only the latest survives, the supersede semantics a content-addressed
    /// store gives editing the body (a new body yields a new id, hence a new
    /// file, which would otherwise coexist with the old one).
    ///
    /// "Same location" is `(target, scope, bundle.position.range)`: re-saving
    /// at one place with changed context replaces what was there; saving at a
    /// *different* range, even on the same file, is an independent note and is
    /// left alone.
    ///
    /// The new note is written **first** (via [`Store::save`]), and only then
    /// are the superseded ones removed, so a crash mid-call leaves the new
    /// note plus possibly some stale siblings, never a hole. This is the
    /// never-silently-dropped invariant applied to supersede.
    ///
    /// Reports what else the file already says, in [`SaveOutcome::neighbours`].
    /// Superseding only collapses notes at the *identical* location, so a
    /// near-duplicate a few lines away is written happily beside the original.
    /// That is how a store fills with restatements and stops being worth
    /// reading, which is the failure that kills a note tool. The walk needed to
    /// supersede already reads every note on the file, so naming the survivors
    /// costs nothing and lets the caller notice it is repeating itself.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if a record or the index cannot be written or
    /// removed, or [`Error::Invalid`] if the index or a note file is
    /// unreadable.
    pub fn save_superseding(&self, note: &Note) -> Result<SaveOutcome> {
        let created = self.save(note)?;

        let mut superseded = 0;
        let mut neighbours = Vec::new();
        // A malformed prior at this location cannot be matched (it will not
        // parse), so it is not superseded here, it stays on disk for `reindex`
        // to surface. Superseding a record we cannot read would be guesswork.
        for prior in self.notes_for(&note.target)?.notes {
            if prior.id == note.id {
                continue;
            }
            let same_location = prior.scope == note.scope
                && prior.bundle.position.range == note.bundle.position.range;
            if same_location {
                self.remove(&prior)?;
                superseded += 1;
            } else {
                neighbours.push(prior);
            }
        }
        // Stable order so the same store always reports the same way, and a
        // caller comparing two saves sees a real change rather than directory
        // iteration order.
        neighbours.sort_by_key(|n| (n.bundle.position.range.start(), n.id.clone()));
        Ok(SaveOutcome {
            created,
            superseded,
            neighbours,
        })
    }

    /// Every note whose stored target is `target` (store-root-relative,
    /// forward-slash), split into records that parsed and records that did not.
    ///
    /// `notes/` is authoritative. The index narrows the healthy fast path, but
    /// every record id absent from it is read from disk and recovered into this
    /// result without rewriting the cache. If the index is missing or malformed,
    /// the method falls back to scanning every record. A malformed unindexed
    /// record has no target to inspect, so it is surfaced for every targeted
    /// read rather than hidden behind an unprovable path assumption.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if `notes/` or the index cannot be read for a reason
    /// other than absence. A rebuildable missing/malformed index is degraded
    /// read state, not an error. A malformed note is reported in
    /// [`NoteScan::malformed`].
    pub fn notes_for(&self, target: &str) -> Result<NoteScan> {
        let (index, index_status) = self.read_index_for_read()?;
        let files = self.note_record_files()?;
        let indexed_targets = reverse_index(&index);
        let indexed_ids: std::collections::BTreeSet<String> =
            indexed_targets.keys().cloned().collect();
        let disk_ids: std::collections::BTreeSet<String> =
            files.iter().filter_map(|f| f.id.clone()).collect();
        let mut scan = NoteScan {
            notes: Vec::new(),
            malformed: Vec::new(),
            index: index_health(index_status, &indexed_ids, &disk_ids),
        };
        let mut seen = std::collections::BTreeSet::new();

        for file in files {
            let cached_target = file
                .id
                .as_ref()
                .and_then(|id| indexed_targets.get(id.as_str()));
            let unindexed = file
                .id
                .as_deref()
                .is_none_or(|id| !indexed_ids.contains(id));
            if !unindexed && cached_target.is_none_or(|cached| cached != target) {
                continue;
            }

            match Self::read_note_at(&file.path) {
                Ok(note) if note.target == target && seen.insert(note.id.clone()) => {
                    scan.notes.push(note);
                }
                Ok(_) => {}
                // Enumeration and read cannot be atomic, so a record listed a
                // moment ago and gone now is a concurrent `delete` (or a
                // `reanchor` supersede), not corruption. Reporting it as
                // malformed would tell the user their store is broken and
                // advise a reindex while nothing is actually wrong.
                Err(Error::Io { source, .. }) if source.kind() == std::io::ErrorKind::NotFound => {
                    tracing::debug!(
                        path = %file.path.display(),
                        "note record vanished mid-scan; a concurrent write removed it"
                    );
                }
                Err(error) => {
                    tracing::warn!(
                        path = %file.path.display(),
                        %error,
                        "unreadable note record; surfacing from notes/ (run a reindex)"
                    );
                    scan.malformed
                        .push(self.malformed_note(file, cached_target, &error));
                }
            }
        }

        for id in index.get(target).into_iter().flatten() {
            if !disk_ids.contains(id) {
                tracing::warn!(
                    note = %id,
                    "indexed note missing on disk; skipping (run a reindex)"
                );
            }
        }
        scan.notes.sort_by(|a, b| a.id.cmp(&b.id));
        scan.malformed.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(scan)
    }

    /// Every record in `notes/`, split into parsed notes and malformed records.
    /// The index contributes cached target information for an unreadable record
    /// but never determines whether that record exists.
    ///
    /// # Errors
    ///
    /// As [`Store::notes_for`].
    pub fn all_notes(&self) -> Result<NoteScan> {
        let (index, index_status) = self.read_index_for_read()?;
        let files = self.note_record_files()?;
        let indexed_targets = reverse_index(&index);
        let indexed_ids: std::collections::BTreeSet<String> =
            indexed_targets.keys().cloned().collect();
        let disk_ids: std::collections::BTreeSet<String> =
            files.iter().filter_map(|f| f.id.clone()).collect();
        let mut scan = NoteScan {
            notes: Vec::new(),
            malformed: Vec::new(),
            index: index_health(index_status, &indexed_ids, &disk_ids),
        };
        let mut seen = std::collections::BTreeSet::new();

        for file in files {
            let cached_target = file
                .id
                .as_ref()
                .and_then(|id| indexed_targets.get(id.as_str()));
            match Self::read_note_at(&file.path) {
                Ok(note) if seen.insert(note.id.clone()) => scan.notes.push(note),
                Ok(note) => {
                    tracing::warn!(
                        path = %file.path.display(),
                        id = %note.id,
                        "duplicate note record on disk; returning it once"
                    );
                }
                // Enumeration and read cannot be atomic, so a record listed a
                // moment ago and gone now is a concurrent `delete` (or a
                // `reanchor` supersede), not corruption. Reporting it as
                // malformed would tell the user their store is broken and
                // advise a reindex while nothing is actually wrong.
                Err(Error::Io { source, .. }) if source.kind() == std::io::ErrorKind::NotFound => {
                    tracing::debug!(
                        path = %file.path.display(),
                        "note record vanished mid-scan; a concurrent write removed it"
                    );
                }
                Err(error) => {
                    tracing::warn!(
                        path = %file.path.display(),
                        %error,
                        "unreadable note record; surfacing from notes/ (run a reindex)"
                    );
                    scan.malformed
                        .push(self.malformed_note(file, cached_target, &error));
                }
            }
        }
        scan.notes
            .sort_by(|a, b| a.target.cmp(&b.target).then(a.id.cmp(&b.id)));
        scan.malformed.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(scan)
    }

    /// Every note whose id starts with `prefix` (case-sensitive hex), in
    /// ascending id order, the lower-level scan primitive. Most callers want
    /// [`Store::match_id_prefix`], which collapses the 0/1/many result into
    /// [`IdMatch`] (pair it with [`crate::validate_id_prefix`] for the
    /// well-formedness policy); reach for this directly only when the raw
    /// match list itself is the point.
    ///
    /// The lookup enumerates content-addressed record paths directly, so a note
    /// remains selectable when the rebuildable index is incomplete or corrupt.
    /// A record that cannot be read or parsed is skipped with a warning. A
    /// consequence is that a *malformed* note cannot
    /// be selected by id-*prefix* (it cannot be read to match), so `update` and
    /// a prefix `delete` cannot reach it. Its removal path is
    /// [`Store::purge_unreadable`], which `delete` invokes for an exact
    /// 64-character id; `doctor`/`reindex` surface that such a record exists.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if `notes/` cannot be enumerated. A malformed note
    /// is skipped, never an error.
    pub fn find_by_id_prefix(&self, prefix: &str) -> Result<Vec<Note>> {
        let mut matches = Vec::new();
        for file in self.note_record_files()? {
            if file.id.as_deref().is_some_and(|id| id.starts_with(prefix)) {
                match Self::read_note_at(&file.path) {
                    Ok(note) => matches.push(note),
                    Err(error) => {
                        tracing::warn!(
                            path = %file.path.display(),
                            %error,
                            "unreadable note record; skipping id lookup"
                        );
                    }
                }
            }
        }
        matches.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(matches)
    }

    /// Resolve an id or hex `prefix` to the single note it selects, reporting
    /// ambiguity and absence as data rather than errors.
    ///
    /// The selection primitive the by-id commands (`show`, `update`, `delete`)
    /// share: it runs [`Store::find_by_id_prefix`] and collapses the result
    /// into [`IdMatch`], [`IdMatch::One`] for a unique hit,
    /// [`IdMatch::Ambiguous`] carrying every candidate when the prefix is not
    /// unique, and [`IdMatch::None`] when nothing matches. Each front-end
    /// renders those three outcomes in its own words (a usage error for the
    /// CLI, a structured result for a server), so the classification stays a
    /// presentation choice and only a genuine store failure is an `Err`.
    ///
    /// Whether `prefix` is well-formed (long enough, hex) is
    /// [`crate::validate_id_prefix`]'s job, deliberately a separate step: this
    /// matcher stays a pure lookup, and a caller that skipped validation
    /// simply gets the same One/Ambiguous/None answer for whatever string it
    /// passed.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if `notes/` cannot be enumerated. A malformed note
    /// is skipped (see [`Store::find_by_id_prefix`]), never an error.
    pub fn match_id_prefix(&self, prefix: &str) -> Result<IdMatch> {
        let mut matches = self.find_by_id_prefix(prefix)?;
        Ok(match matches.pop() {
            None => IdMatch::None,
            Some(only) if matches.is_empty() => IdMatch::One(only),
            Some(last) => {
                // More than one match: restore the popped id (it sorts last, so
                // pushing it back keeps the ascending candidate order intact).
                matches.push(last);
                IdMatch::Ambiguous(matches)
            }
        })
    }

    /// Removes a note: de-indexes it, then deletes its record. Used by
    /// `reanchor` to retire the note a refreshed one supersedes. A
    /// already-missing record is not an error (the goal state is reached).
    ///
    /// Runs the index update under the store's exclusive index lock so a
    /// remove cannot race a concurrent save's index write.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if the index or record cannot be written/removed,
    /// or [`Error::Invalid`] if the index is unreadable.
    pub fn remove(&self, note: &Note) -> Result<()> {
        self.with_index_lock(|| {
            let mut index = self.read_index()?;
            self.repair_git_config_files();
            if let Some(ids) = index.get_mut(&note.target) {
                ids.retain(|i| i != &note.id);
                if ids.is_empty() {
                    index.remove(&note.target);
                }
            }
            self.write_index(&index)
        })?;

        let path = self.note_path(&note.id);
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(()),
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(source) => Err(Error::Io { path, source }),
        }
    }

    /// Purges an *unreadable* note record named by its exact content `id`: drops
    /// any index pointer to it and unlinks the file. The deliberate removal path
    /// for a corrupt record that [`Store::find_by_id_prefix`] cannot reach,
    /// such a record cannot be parsed, so it cannot be matched by prefix, yet
    /// its id is recoverable from its filename and is shown in `query`/`doctor`
    /// output for exactly this purpose.
    ///
    /// Guarded two ways so it can never destroy a healthy note through this
    /// preview-less path:
    ///
    /// - It acts only on the *exact* id: a short prefix maps to an on-disk
    ///   record path that does not exist, so a prefix yields `Ok(false)`.
    /// - It refuses a *readable* record: if the file parses as a valid note,
    ///   this returns `Ok(false)` and removes nothing, a real note must go
    ///   through `delete`, which shows what it is removing.
    ///
    /// Returns `Ok(true)` when an unreadable record was found at the id's path
    /// (and, unless `dry_run`, removed), `Ok(false)` when no such record exists
    /// or the file was actually readable. With `dry_run` the readability check
    /// still runs but nothing is written.
    ///
    /// The de-index runs under the store's exclusive index lock, matching
    /// [`Store::remove`]. The id's target is unknown (the file is unparseable),
    /// so every target's id list is scanned. Like every mutation other than
    /// `reindex`, it refuses a missing or malformed index before deleting data.
    ///
    /// # Errors
    ///
    /// [`Error::Io`] if the index or record file cannot be written/removed, or
    /// [`Error::IndexMalformed`]/[`Error::IndexMissing`] when the cache must be
    /// repaired before deletion.
    pub fn purge_unreadable(&self, id: &str, dry_run: bool) -> Result<bool> {
        let path = self.note_path(id);
        match Self::read_note_at(&path) {
            // A readable note is not ours to purge, `delete` owns that, with a
            // preview. Decline rather than bypass it.
            Ok(_) => return Ok(false),
            // No file at this exact id: nothing to purge (the prefix-guard case
            // lands here, since a prefix names no real record file).
            Err(Error::Io { source, .. }) if source.kind() == std::io::ErrorKind::NotFound => {
                return Ok(false);
            }
            // Anything else (unparseable JSON, a non-NotFound read error) is the
            // corrupt record this exists to clear.
            Err(_) => {}
        }

        if dry_run {
            return Ok(true);
        }

        self.with_index_lock(|| {
            let mut index = self.read_index()?;
            self.repair_git_config_files();
            index.retain(|_target, ids| {
                ids.retain(|i| i != id);
                !ids.is_empty()
            });
            self.write_index(&index)
        })?;

        match std::fs::remove_file(&path) {
            Ok(()) => Ok(true),
            // Already gone (a concurrent purge, a manual `rm`): the goal state
            // is reached, so report success.
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(true),
            Err(source) => Err(Error::Io { path, source }),
        }
    }

    /// Rebuilds the by-path index from the note records on disk.
    ///
    /// The index (`index/by-path.json`) is a cache, never the source of truth:
    /// as this module's header records, it can always be regenerated by
    /// scanning `notes/`. This is the deliberate repair pass behind the
    /// "run a reindex" advisory that [`Store::notes_for`] and
    /// [`Store::find_by_id_prefix`] log when an index pointer no longer
    /// resolves to a file.
    ///
    /// It walks `notes/<aa>/<rest>.json`, reads each record, and rebuilds the
    /// `target -> [id]` map from the notes themselves, so an id present on
    /// disk but missing from the index is recovered, and an index pointer with
    /// no file behind it is dropped. A file that cannot be parsed as a note is
    /// recorded in [`ReindexReport::malformed`] and skipped: one corrupt
    /// record must neither sink the rebuild nor be silently discarded
    /// (invariant #4).
    ///
    /// This is a *maintenance* write over the index alone, it never invokes
    /// the anchor ladder, so it is not a resolve and does not bear on invariant
    /// #8 (only `reanchor` writes at resolve time). With `dry_run`, the report
    /// is computed but the on-disk index is left untouched.
    ///
    /// The scan and the rewrite run under the store's exclusive index lock, so
    /// reindex never interleaves with another index read-modify-write. The lock
    /// does not freeze `notes/`, so the scan is *not* an atomic snapshot of the
    /// directory; two races are worth naming, both benign:
    ///
    /// - A concurrent `save` writes its note file *before* taking the lock to
    ///   index it. If the scan misses that file, the save's `index_note` is
    ///   idempotent and serialised behind the same lock, so it re-adds the
    ///   pointer once reindex releases, the note is never lost. (The guarantee
    ///   rests on that idempotent re-index, not on the scan seeing every file.)
    /// - A concurrent `remove` de-indexes under the lock but unlinks the file
    ///   *after* releasing it. A scan in that window may re-add a pointer to a
    ///   file about to vanish, a transient dangling pointer the next reindex
    ///   drops. Reindex is idempotent, so this self-heals.
    ///
    /// # Errors
    ///
    /// [`Error::Io`] if a `notes/` directory cannot be enumerated or the
    /// rebuilt index cannot be written. A single note file whose *contents*
    /// are unreadable or unparseable is reported in
    /// [`ReindexReport::malformed`], not surfaced as an error.
    pub fn reindex(&self, dry_run: bool) -> Result<ReindexReport> {
        self.with_index_lock(|| {
            let scan = self.compute_scan()?;
            if !dry_run {
                self.write_index(&scan.rebuilt)?;
                self.repair_git_config_files();
            }
            Ok(ReindexReport {
                dry_run,
                scanned: scan.scanned,
                indexed: scan.indexed,
                recovered: scan.recovered,
                dangling: scan.dangling,
                malformed: scan.malformed,
            })
        })
    }

    /// Walk `notes/` and diff the records found against the current index,
    /// without writing anything or taking the lock. The shared core of both
    /// [`Store::reindex`] (which wraps it in the lock and then writes the
    /// rebuilt index) and [`Store::health`] (which only reports the diff).
    ///
    /// Because it takes no lock it is *not* an atomic snapshot of `notes/`; the
    /// races [`Store::reindex`] documents apply, all benign, a read-only
    /// caller tolerates a transient over/under-count, and `reindex` re-runs the
    /// same scan under the lock before it commits.
    ///
    /// A malformed index is treated as an empty baseline (so every on-disk note
    /// shows up as `recovered`) rather than an error: the notes are the source
    /// of truth, and this is exactly the corruption a rebuild exists to repair.
    ///
    /// # Errors
    ///
    /// [`Error::Io`] if a `notes/` directory cannot be enumerated, or any index
    /// read error other than the rebuildable [`Error::IndexMalformed`]/
    /// [`Error::IndexMissing`]. A single unreadable *note* is collected into
    /// [`ScanOutcome::malformed`], never surfaced as an error.
    fn compute_scan(&self) -> Result<ScanOutcome> {
        // The notes on disk are the source of truth; the scan must run even
        // when the cache it diffs against is itself unreadable (a mangled
        // merge, a hand-edit). A malformed index is treated as an empty
        // baseline so every on-disk note shows up as `recovered`; a genuine
        // I/O failure still propagates.
        let index_exists = self.index_path().is_file();
        let (previous, index_status): (std::collections::BTreeSet<String>, IndexStatus) =
            match self.read_index() {
                Ok(index) => (
                    index.into_values().flatten().collect(),
                    if index_exists {
                        IndexStatus::Healthy
                    } else {
                        IndexStatus::Missing
                    },
                ),
                Err(Error::IndexMissing { .. }) => {
                    tracing::warn!("existing index is unreadable; rebuilding from notes/");
                    (std::collections::BTreeSet::new(), IndexStatus::Missing)
                }
                Err(Error::IndexMalformed { .. }) => {
                    tracing::warn!("existing index is unreadable; rebuilding from notes/");
                    (std::collections::BTreeSet::new(), IndexStatus::Malformed)
                }
                Err(other) => return Err(other),
            };

        let mut rebuilt = IndexMap::new();
        // The distinct ids seen on disk. Doubles as the dedup guard during the
        // walk and as the `current` set for the recovered/dangling diff
        // afterwards, so a content id is indexed exactly once.
        let mut seen = std::collections::BTreeSet::new();
        let mut scanned = 0usize;
        let mut malformed = Vec::new();

        let notes_dir = self.notes_dir();
        match std::fs::read_dir(&notes_dir) {
            Ok(prefixes) => {
                for prefix in prefixes {
                    let prefix = prefix.map_err(|source| Error::Io {
                        path: notes_dir.clone(),
                        source,
                    })?;
                    let prefix_path = prefix.path();
                    // Only the two-char fan-out directories hold notes; ignore
                    // any stray file sitting at the top of `notes/`.
                    if !prefix_path.is_dir() {
                        continue;
                    }
                    for file in std::fs::read_dir(&prefix_path).map_err(|source| Error::Io {
                        path: prefix_path.clone(),
                        source,
                    })? {
                        let file = file.map_err(|source| Error::Io {
                            path: prefix_path.clone(),
                            source,
                        })?;
                        let path = file.path();
                        // A note record is `<rest>.json`. Skip anything else,
                        // a tempfile caught mid-rename, an editor backup, a
                        // nested directory.
                        if path.extension().and_then(std::ffi::OsStr::to_str) != Some("json") {
                            continue;
                        }
                        match Self::read_note_at(&path) {
                            Ok(note) => {
                                scanned += 1;
                                if seen.insert(note.id.clone()) {
                                    rebuilt.entry(note.target).or_default().push(note.id);
                                } else {
                                    // Two files carry the same content id, only
                                    // possible if a record was copied, since
                                    // `save` writes one file per id. Index it
                                    // once, but surface the duplicate: silently
                                    // merging it would leave an unexplained
                                    // `scanned` > `indexed` gap.
                                    tracing::warn!(
                                        path = %path.display(),
                                        id = %note.id,
                                        "duplicate note record on disk; indexing once (reindex)"
                                    );
                                }
                            }
                            Err(error) => {
                                tracing::warn!(
                                    path = %path.display(),
                                    %error,
                                    "unreadable note record; skipping (reindex)"
                                );
                                malformed.push(path);
                            }
                        }
                    }
                }
            }
            // No `notes/` directory: the store holds nothing, so it scans to an
            // empty result rather than erroring, the goal state is reachable.
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(Error::Io {
                    path: notes_dir,
                    source,
                });
            }
        }

        // `seen` is exactly the distinct ids found on disk. `BTreeSet`'s
        // `difference` yields ascending order, so both lists are deterministic
        // without an extra sort.
        let current = seen;
        let recovered = current.difference(&previous).cloned().collect();
        let dangling = previous.difference(&current).cloned().collect();
        let indexed = current.len();

        Ok(ScanOutcome {
            rebuilt,
            scanned,
            indexed,
            recovered,
            dangling,
            malformed,
            index_status,
        })
    }

    /// A read-only health report on the store: malformed records, index drift,
    /// and any missing managed `.gitattributes` lines. The backing for
    /// `ynotes doctor`'s health block.
    ///
    /// Strictly read-only and **lock-free**, it writes nothing and does not
    /// take the index lock, so it honours `doctor`'s "mutates nothing" contract
    /// (a diagnostic must not perturb what it diagnoses). Being lock-free it is
    /// best-effort under concurrent writers; for a one-shot `doctor` that is the
    /// right trade.
    ///
    /// # Errors
    ///
    /// [`Error::Io`] if a `notes/` directory or `.gitattributes` cannot be
    /// read for a reason other than absence. A malformed index is treated as
    /// empty (it is what this diagnoses, not an error), and an unreadable note
    /// is reported in [`StoreHealth::malformed`] rather than surfaced as an
    /// error.
    pub fn health(&self) -> Result<StoreHealth> {
        let scan = self.compute_scan()?;
        // A malformed file's id is in the index (it was a real note) but absent
        // from the rebuilt set (it would not parse), so the recovered/dangling
        // diff counts it as `dangling`. For a *diagnostic* that double-counts
        // one bad record as both `malformed` and `dangling`. Attribute it to
        // exactly one bucket, `malformed`, by excluding malformed-file ids
        // (recoverable from the filename) from the dangling count, so `dangling`
        // means strictly "an index pointer with no file behind it at all".
        let malformed_ids: std::collections::BTreeSet<String> = scan
            .malformed
            .iter()
            .filter_map(|p| Self::id_from_note_path(p))
            .collect();
        let dangling = scan
            .dangling
            .iter()
            .filter(|id| !malformed_ids.contains(id.as_str()))
            .count();
        Ok(StoreHealth {
            malformed: scan.malformed,
            index: IndexHealth {
                status: scan.index_status,
                recovered: scan.recovered.len(),
                dangling,
            },
            gitattributes_missing: self.missing_gitattributes(),
        })
    }

    /// The managed `.gitattributes` lines absent from `.ynotes/.gitattributes`
    ///, the read-only counterpart of [`Self::write_git_config_files`]. A
    /// non-empty result on a *shared* store means the merge guards (the
    /// `merge=union` index and the `notes/** -merge` rule) are not in force, so
    /// a future merge could corrupt the store; `init`/`reindex` re-add them.
    ///
    /// A file that cannot be read at all counts every managed line as missing.
    /// The guards demonstrably are not in force from this process's point of
    /// view, and that is the actionable answer; erroring instead would make
    /// `doctor` fail on precisely the store whose git integration is broken,
    /// which is the one worth diagnosing.
    ///
    fn missing_gitattributes(&self) -> Vec<String> {
        let path = self.root.join(".gitattributes");
        let existing = std::fs::read_to_string(&path).unwrap_or_default();
        let has_pattern = |pat: &str| {
            existing
                .lines()
                .any(|l| l.split_whitespace().next() == Some(pat))
        };
        GITATTRIBUTES_MANAGED
            .iter()
            .filter(|m| !has_pattern(m.pattern))
            .map(|m| m.line.to_owned())
            .collect()
    }

    fn notes_dir(&self) -> PathBuf {
        self.root.join("notes")
    }

    /// Read the rebuildable index for a non-mutating operation. Missing or
    /// malformed cache state degrades to an empty accelerator so the caller can
    /// recover from `notes/`; all other I/O failures remain real errors.
    fn read_index_for_read(&self) -> Result<(IndexMap, IndexStatus)> {
        let exists = self.index_path().is_file();
        match self.read_index() {
            Ok(index) => Ok((
                index,
                if exists {
                    IndexStatus::Healthy
                } else {
                    IndexStatus::Missing
                },
            )),
            Err(Error::IndexMissing { .. }) => {
                tracing::warn!("index cache is unreadable; serving records from notes/");
                Ok((IndexMap::new(), IndexStatus::Missing))
            }
            Err(Error::IndexMalformed { .. }) => {
                tracing::warn!("index cache is unreadable; serving records from notes/");
                Ok((IndexMap::new(), IndexStatus::Malformed))
            }
            Err(other) => Err(other),
        }
    }

    /// Enumerate every JSON record below the fan-out directories in `notes/`.
    /// Paths are sorted so every read is deterministic regardless of filesystem
    /// directory order. Enumeration does not parse a record and never writes.
    fn note_record_files(&self) -> Result<Vec<RecordFile>> {
        let notes_dir = self.notes_dir();
        let prefixes = match std::fs::read_dir(&notes_dir) {
            Ok(prefixes) => prefixes,
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
            Err(source) => {
                return Err(Error::Io {
                    path: notes_dir,
                    source,
                });
            }
        };
        let mut files = Vec::new();
        for prefix in prefixes {
            let prefix = prefix.map_err(|source| Error::Io {
                path: notes_dir.clone(),
                source,
            })?;
            let prefix_path = prefix.path();
            if !prefix_path.is_dir() {
                continue;
            }
            for file in std::fs::read_dir(&prefix_path).map_err(|source| Error::Io {
                path: prefix_path.clone(),
                source,
            })? {
                let file = file.map_err(|source| Error::Io {
                    path: prefix_path.clone(),
                    source,
                })?;
                let path = file.path();
                if path.extension().and_then(std::ffi::OsStr::to_str) == Some("json") {
                    files.push(RecordFile {
                        id: Self::id_from_note_path(&path),
                        path,
                    });
                }
            }
        }
        files.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(files)
    }

    /// Build the public malformed-record shape from the facts still recoverable
    /// without parsing its contents.
    fn malformed_note(
        &self,
        file: RecordFile,
        cached_target: Option<&String>,
        error: &Error,
    ) -> MalformedNote {
        let path = file
            .path
            .strip_prefix(&self.root)
            .map_or_else(|_| file.path.clone(), Path::to_path_buf);
        MalformedNote {
            id: file.id,
            target: cached_target.cloned(),
            path: to_forward_slash(&path),
            error: error.to_string(),
        }
    }

    /// Whether `notes/` holds at least one note record on disk. Used to tell a
    /// deleted index (notes still present, a recoverable problem) from a
    /// genuinely empty store (no notes, not a problem). Best-effort: any read
    /// error means "treat as empty", so this can never turn a transient I/O
    /// hiccup into a false `IndexMissing`.
    fn has_note_records(&self) -> bool {
        let Ok(prefixes) = std::fs::read_dir(self.notes_dir()) else {
            return false;
        };
        for prefix in prefixes.flatten() {
            let name = prefix.file_name();
            if name.to_string_lossy().len() == 2
                && prefix.path().is_dir()
                && let Ok(files) = std::fs::read_dir(prefix.path())
            {
                for f in files.flatten() {
                    if f.path().extension().and_then(std::ffi::OsStr::to_str) == Some("json") {
                        return true;
                    }
                }
            }
        }
        false
    }

    fn index_dir(&self) -> PathBuf {
        self.root.join("index")
    }

    fn index_path(&self) -> PathBuf {
        self.index_dir().join("by-path.json")
    }

    fn head_path(&self) -> PathBuf {
        self.root.join("HEAD")
    }

    /// `notes/<first two hex chars>/<rest>.json`.
    ///
    /// Ids are content-addressed SHA-256, always 64 lowercase hex characters
    /// ([`crate::note::Note::new`] enforces this by construction), so the
    /// split point is unconditional, no need to clamp to `id.len()`.
    fn note_path(&self, id: &str) -> PathBuf {
        let (prefix, rest) = id.split_at(2);
        self.notes_dir().join(prefix).join(format!("{rest}.json"))
    }

    /// The note id a `notes/<aa>/<rest>.json` path encodes, the inverse of
    /// [`Self::note_path`], if the path has that shape and yields a
    /// 64-character lowercase-hex id.
    ///
    /// A malformed file cannot be parsed for its id from the inside, but its
    /// *filename* still carries it. [`Self::health`] uses this to attribute a
    /// corrupt record to its id, so it can keep that record out of the
    /// `dangling` count (it belongs in `malformed`). Returns `None` for any
    /// path that does not look like a record, so a stray file is never mistaken
    /// for one.
    fn id_from_note_path(path: &Path) -> Option<String> {
        let rest = path.file_stem()?.to_str()?;
        let prefix = path.parent()?.file_name()?.to_str()?;
        let id = format!("{prefix}{rest}");
        is_note_id(&id).then_some(id)
    }

    /// Reads and parses the note record at `path` directly. The seam `reindex`
    /// needs: it discovers note files by walking `notes/` and so has a path in
    /// hand, not an id. It is an associated function because it needs only the
    /// path, not a store handle.
    fn read_note_at(path: &Path) -> Result<Note> {
        let bytes = std::fs::read(path).map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })?;
        serde_json::from_slice(&bytes).map_err(|e| {
            Error::Invalid(format!("note `{}` is malformed JSON: {e}", path.display()))
        })
    }

    /// Reads and parses the by-path index from disk.
    ///
    /// This is the strict primitive used by mutation paths: `IndexMissing`
    /// (raised when the file is absent but records survive) and
    /// `IndexMalformed` refuse a write before note data changes. Read paths wrap
    /// it with [`Self::read_index_for_read`], degrade to record enumeration, and
    /// report the cache status without writing. `reindex` is the sole repair
    /// path and treats either condition as an empty baseline.
    fn read_index(&self) -> Result<IndexMap> {
        let path = self.index_path();
        let bytes = match std::fs::read(&path) {
            Ok(bytes) => bytes,
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
                // A missing index over a non-empty `notes/` is recoverable
                // corruption, not emptiness: surface it so reads do not read as
                // "no notes" (silent apparent data loss). An empty store legitimately
                // has no records, so it stays an empty result.
                if self.has_note_records() {
                    return Err(Error::IndexMissing { path });
                }
                return Ok(IndexMap::new());
            }
            Err(source) => return Err(Error::Io { path, source }),
        };
        let mut index = Self::parse_index(&bytes, &path)?;
        // A union merge can leave duplicate or out-of-order ids; collapse them
        // so callers always see a canonical, duplicate-free view regardless of
        // how git left the file on disk.
        for ids in index.values_mut() {
            ids.sort();
            ids.dedup();
        }
        Ok(index)
    }

    /// Parse index bytes, accepting both the current JSONL format and the
    /// legacy single-object format (so a store written by an older ynotes still
    /// opens). An empty/whitespace file is an empty index.
    ///
    /// # Errors
    ///
    /// [`Error::IndexMalformed`] if the bytes parse as neither format.
    fn parse_index(bytes: &[u8], path: &Path) -> Result<IndexMap> {
        if bytes.iter().all(u8::is_ascii_whitespace) {
            return Ok(IndexMap::new());
        }
        // Legacy nested-object format first. A multi-entry JSONL file is not a
        // valid single object, and a single JSONL line fails to parse as
        // `BTreeMap<String, Vec<String>>` (its values are strings, not arrays),
        // so detection is unambiguous.
        if let Ok(map) = serde_json::from_slice::<IndexMap>(bytes) {
            validate_index_ids(&map, path)?;
            return Ok(map);
        }
        let text = std::str::from_utf8(bytes).map_err(|_| Error::IndexMalformed {
            path: path.to_path_buf(),
        })?;
        let mut map = IndexMap::new();
        for line in text.lines() {
            let line = line.trim();
            if line.is_empty() {
                continue;
            }
            let entry: IndexLine =
                serde_json::from_str(line).map_err(|_| Error::IndexMalformed {
                    path: path.to_path_buf(),
                })?;
            if !is_note_id(&entry.id) {
                return Err(Error::IndexMalformed {
                    path: path.to_path_buf(),
                });
            }
            map.entry(entry.target).or_default().push(entry.id);
        }
        Ok(map)
    }

    /// Ensure the store's git-integration files carry their managed lines.
    /// Idempotent and non-clobbering: a managed line is appended only when no
    /// existing line targets its pattern, and existing lines are never changed.
    /// This both equips a fresh store and upgrades one created before a managed
    /// line existed (the `notes/** -merge` guard). Lets a committed `.ynotes/`
    /// merge with zero per-clone git setup.
    fn write_git_config_files(&self) -> Result<()> {
        ensure_managed_lines(&self.root.join(".gitattributes"), GITATTRIBUTES_MANAGED)?;
        ensure_managed_lines(&self.root.join(".gitignore"), GITIGNORE_MANAGED)?;
        Ok(())
    }

    /// [`write_git_config_files`](Self::write_git_config_files) as a
    /// best-effort errand that never fails the caller's mutation.
    ///
    /// These lines are git-integration hygiene, not store state: the store is
    /// fully functional without them, and [`health`](Self::health) reports the
    /// gap durably as `gitattributes_missing`. A `.gitattributes` that cannot
    /// be maintained, read-only, or replaced by a directory, must not be able
    /// to block a `delete`, which is the very command for getting rid of a bad
    /// note. A genuinely unwritable store still surfaces, because the index
    /// write that follows every one of these call sites is not best-effort.
    ///
    /// `init` deliberately does *not* use this: creating the files is part of
    /// what initialisation promises, so a failure there is a real failure.
    fn repair_git_config_files(&self) {
        if let Err(e) = self.write_git_config_files() {
            tracing::warn!(
                error = %e,
                "could not refresh the store's managed git files; `ynotes doctor` reports the gap"
            );
        }
    }

    fn write_index(&self, index: &IndexMap) -> Result<()> {
        // Sorted JSONL, one entry per line. Sorting (targets via the BTreeMap,
        // ids here) plus dedup makes the file byte-identical regardless of
        // insertion order, which keeps shared-store diffs minimal and union
        // merges clean.
        let mut buf = String::new();
        for (target, ids) in index {
            let mut ids: Vec<&String> = ids.iter().collect();
            ids.sort();
            ids.dedup();
            for id in ids {
                let line = serde_json::to_string(&IndexLine {
                    target: target.clone(),
                    id: id.clone(),
                })
                .map_err(|e| Error::Invalid(format!("cannot serialise index: {e}")))?;
                buf.push_str(&line);
                buf.push('\n');
            }
        }
        write_file(&self.index_path(), buf.as_bytes())
    }

    /// Run `f` while holding the store's exclusive advisory lock on
    /// `.ynotes/lock`. The index is a rebuildable cache, but the
    /// read-modify-write that maintains it must be serialised across processes
    /// or two concurrent writers will lose each other's edits.
    ///
    /// The lock is released when the borrowed [`std::fs::File`] is dropped at
    /// the end of this scope, even if `f` panicked; the explicit `unlock`
    /// keeps that release visible at the call site rather than implicit in
    /// drop order.
    fn with_index_lock<R>(&self, f: impl FnOnce() -> Result<R>) -> Result<R> {
        let path = self.root.join(LOCK_FILENAME);
        let file = std::fs::OpenOptions::new()
            .create(true)
            .read(true)
            .write(true)
            .truncate(false)
            .open(&path)
            .map_err(|source| Error::Io {
                path: path.clone(),
                source,
            })?;
        file.lock_exclusive().map_err(|source| Error::Io {
            path: path.clone(),
            source,
        })?;
        let result = f();
        // Best-effort: the OS releases the lock on drop too, so a failure
        // here cannot strand the store; surfacing it would mask the real
        // error from `f`. Named (not `_`) to satisfy `let_underscore_drop`.
        let _unlocked = FileExt::unlock(&file);
        result
    }
}

/// Invert the cache so an unreadable record can still inherit the target its
/// index pointer carried. Duplicate ids are already collapsed within a target;
/// if a corrupt cache assigns one id to several targets, the first sorted target
/// wins only as diagnostic context and the record remains visibly malformed.
fn reverse_index(index: &IndexMap) -> std::collections::BTreeMap<String, String> {
    let mut reverse = std::collections::BTreeMap::new();
    for (target, ids) in index {
        for id in ids {
            reverse.entry(id.clone()).or_insert_with(|| target.clone());
        }
    }
    reverse
}

/// Compare identities encoded by record paths with identities in the index.
/// This calculation is metadata-only, so a targeted query can report global
/// drift without parsing unrelated note bodies.
fn index_health(
    status: IndexStatus,
    indexed: &std::collections::BTreeSet<String>,
    on_disk: &std::collections::BTreeSet<String>,
) -> IndexHealth {
    IndexHealth {
        status,
        recovered: on_disk.difference(indexed).count(),
        dangling: indexed.difference(on_disk).count(),
    }
}

/// Nearest ancestor (including `start`) containing `.git`, dir or file.
///
/// A worktree's `.git` is a file, not a directory, so existence, not
/// directoryness, is the test; this is what lets [`Store::discover_or_init_from`]
/// anchor a new store at a worktree root as readily as at a plain clone.
fn find_git_root(start: &Path) -> Option<std::path::PathBuf> {
    start
        .ancestors()
        .find(|d| d.join(".git").exists())
        .map(Path::to_path_buf)
}

/// Smallest accepted id prefix. Four hex characters distinguish 65,536 ids,
/// enough headroom for ergonomic short forms while keeping a stray single
/// character (`ynotes delete a`) from accidentally matching anything.
const MIN_PREFIX: usize = 4;

/// Reject a malformed note-id prefix (non-hex or shorter than four
/// characters) up front, so a caller mistake surfaces as a usage-class error
/// rather than a runtime "not found".
///
/// The well-formedness policy every front-end shares, engine-owned so two
/// front-ends cannot drift on what counts as a valid selector. Deliberately
/// separate from [`Store::match_id_prefix`]: validation is an input check on
/// the caller's string, matching is a pure lookup, a front-end calls this
/// first, then matches.
///
/// # Errors
///
/// [`Error::InvalidIdPrefix`] if `prefix` is shorter than four characters or
/// contains a character outside lowercase hex (ids are always emitted
/// lowercase, so an uppercase prefix could never match and is refused up
/// front rather than dead-ending as "not found").
pub fn validate_id_prefix(prefix: &str) -> Result<()> {
    if prefix.len() < MIN_PREFIX {
        return Err(Error::InvalidIdPrefix(format!(
            "`{prefix}` is too short: id prefixes must be at least {MIN_PREFIX} hex characters"
        )));
    }
    if !prefix
        .bytes()
        .all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
    {
        return Err(Error::InvalidIdPrefix(format!(
            "`{prefix}` is not a valid note id (expected lowercase hex)"
        )));
    }
    Ok(())
}

/// The shared "ambiguous prefix" wording: the requested prefix, the candidate
/// count, and each candidate's first 16 hex characters. Both front-ends render
/// ambiguity through this one function so the message cannot drift between the
/// CLI (`update`/`show`) and the MCP `notes` tool.
pub fn ambiguous_id_message(requested: &str, candidates: &[Note]) -> String {
    let n = candidates.len();
    let listed: Vec<String> = candidates
        .iter()
        .map(|m| m.id.chars().take(16).collect::<String>())
        .collect();
    format!(
        "`{requested}` is ambiguous, {n} candidates: {}",
        listed.join(", ")
    )
}

/// Rejects an index whose entries point at a value that is not a note id as
/// [`Error::IndexMalformed`], so a hand-edited or damaged `by-path.json` surfaces
/// the reindex-repair path instead of carrying a malformed id into the
/// two-character fan-out that derives a record's path (invariant #4).
fn validate_index_ids(index: &IndexMap, path: &Path) -> Result<()> {
    if index.values().flatten().all(|id| is_note_id(id.as_str())) {
        Ok(())
    } else {
        Err(Error::IndexMalformed {
            path: path.to_path_buf(),
        })
    }
}

/// Whether `id` is a well-formed note id: a 64-character lowercase-hex SHA-256
/// digest. A note id is a content hash (invariant #6), so anything shorter or
/// non-hex is corruption, and feeding it to the two-character fan-out would
/// slice a too-short string.
fn is_note_id(id: &str) -> bool {
    id.len() == 64 && id.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

/// Creates `dir` and all parents, mapping failure to a path-carrying
/// [`Error::Io`].
fn mkdir(dir: &Path) -> Result<()> {
    std::fs::create_dir_all(dir).map_err(|source| Error::Io {
        path: dir.to_path_buf(),
        source,
    })
}

/// Writes `bytes` to `path` atomically: a temp file in the same directory,
/// then a rename. A crash leaves either the old file or the new one, never a
/// truncated mix. Overwrites any existing file
/// at `path`, used for the index and the HEAD sentinel, whose contents
/// must be updated in place.
fn write_file(path: &Path, bytes: &[u8]) -> Result<()> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let io = |source| Error::Io {
        path: path.to_path_buf(),
        source,
    };
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(io)?;
    tmp.write_all(bytes).map_err(io)?;
    tmp.flush().map_err(io)?;
    tmp.persist(path).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e.error,
    })?;
    Ok(())
}

/// Append any missing `managed` lines to `path`, leaving existing content
/// untouched. A managed line is "present" when some non-empty existing line's
/// first whitespace-delimited token equals its `pattern`. Writes only when at
/// least one line is missing; creates the file (with all managed lines) if it
/// does not exist. The whole file is rewritten atomically via [`write_file`].
fn ensure_managed_lines(path: &Path, managed: &[ManagedLine]) -> Result<()> {
    let existing = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(source) => {
            return Err(Error::Io {
                path: path.to_path_buf(),
                source,
            });
        }
    };
    let has_pattern = |pat: &str| {
        existing
            .lines()
            .any(|l| l.split_whitespace().next() == Some(pat))
    };
    let missing: Vec<&ManagedLine> = managed.iter().filter(|m| !has_pattern(m.pattern)).collect();
    if missing.is_empty() {
        return Ok(());
    }
    let mut out = existing;
    // Guarantee the appended block starts on its own line.
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    for m in missing {
        out.push_str(m.line);
        out.push('\n');
    }
    write_file(path, out.as_bytes())
}

/// Like [`write_file`] but refuses to overwrite, returns `Ok(false)` if
/// `path` already exists, `Ok(true)` on a fresh write.
///
/// The rename-no-replace is atomic (POSIX `link` + `unlink`-on-tmp, Windows
/// `MoveFileExW` without `MOVEFILE_REPLACE_EXISTING`), closing the
/// check-then-write TOCTOU window that previously let two concurrent
/// identical [`Store::save`] calls both report `created: true`. The temp
/// file is dropped (and removed from disk) on the lost-race path.
fn write_file_noclobber(path: &Path, bytes: &[u8]) -> Result<bool> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let io = |source| Error::Io {
        path: path.to_path_buf(),
        source,
    };
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(io)?;
    tmp.write_all(bytes).map_err(io)?;
    tmp.flush().map_err(io)?;
    match tmp.persist_noclobber(path) {
        Ok(_) => Ok(true),
        Err(e) if e.error.kind() == std::io::ErrorKind::AlreadyExists => Ok(false),
        Err(e) => Err(Error::Io {
            path: path.to_path_buf(),
            source: e.error,
        }),
    }
}
