//! The Claude Code plugin manifests and the discovery stub are repo content
//! the binary never reads. These tests keep them valid JSON, version-synced
//! with the crate (invariant 9), and shaped the way Claude Code's plugin
//! loader expects, so a hand edit cannot ship a broken plugin.

use std::fs;
use std::path::{Path, PathBuf};

/// The repository root, two levels above this crate's manifest dir.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/ynotes-cli sits two levels below the repo root")
        .to_path_buf()
}

#[test]
fn plugin_manifest_is_valid_version_synced_and_registers_the_mcp_server() {
    let raw = fs::read_to_string(repo_root().join(".claude-plugin/plugin.json"))
        .expect("plugin.json exists");
    let json: serde_json::Value = serde_json::from_str(&raw).expect("plugin.json is valid JSON");
    assert_eq!(json["name"], "ynotes");
    // Generated by scripts/sync-version.mjs; the version-sync CI job fails on
    // drift, and this pin fails the test suite too.
    assert_eq!(json["version"], env!("CARGO_PKG_VERSION"));
    assert_eq!(json["mcpServers"]["ynotes"]["command"], "ynotes");
    assert_eq!(
        json["mcpServers"]["ynotes"]["args"],
        serde_json::json!(["mcp"])
    );
}

#[test]
fn marketplace_manifest_lists_the_one_plugin_rooted_at_the_repo() {
    let raw = fs::read_to_string(repo_root().join(".claude-plugin/marketplace.json"))
        .expect("marketplace.json exists");
    let json: serde_json::Value =
        serde_json::from_str(&raw).expect("marketplace.json is valid JSON");
    assert_eq!(json["name"], "ynotes");
    assert_eq!(json["plugins"][0]["name"], "ynotes");
    assert_eq!(json["plugins"][0]["source"], "./");
}

#[test]
fn the_stub_skill_is_a_pointer_not_a_guide() {
    let stub = fs::read_to_string(repo_root().join("skills/ynotes/SKILL.md"))
        .expect("the discovery stub exists");
    assert_eq!(stub.lines().next(), Some("---"), "frontmatter present");
    assert!(
        stub.contains("ynotes skills get core"),
        "the stub must point at the binary-served content"
    );
    assert!(
        stub.lines().count() <= 60,
        "the stub must stay a pointer, content belongs in the binary, where it is versioned with the release"
    );
}
