//! The on-disk note store: a `.ynotes/` directory backed by a
//! content-addressed object store.
//!
//! Layout:
//!
//! ```text
//! .ynotes/
//!   HEAD                     format sentinel; its presence marks the root
//!   notes/<aa>/<rest>.json   one note per file, fanned out by id prefix
//!   index/by-path.json       target-path -> [note id, ...]
//! ```
//!
//! Two rules the rest of the engine relies on:
//!
//! 1. **Note files are immutable and content-addressed.** They are written to
//!    a temp file in the same directory and atomically renamed into place, so
//!    a crash never leaves a half-written note.
//! 2. **The index is a rebuildable cache, not the source of truth.** It can be
//!    regenerated by scanning `notes/`. A corrupt index must never cost a
//!    note — this is the storage face of the never-silently-dropped invariant.

use std::io::Write as _;
use std::path::{Path, PathBuf};

use fs4::fs_std::FileExt;

use crate::error::{Error, Result};
use crate::note::Note;
use crate::path::{canonical_for_compare, to_forward_slash};

/// Directory name of the store, created at a project root.
const STORE_DIRNAME: &str = ".ynotes";

/// Contents of the `HEAD` sentinel; the integer is the store format version.
const HEAD_CONTENTS: &str = "ynotes 1\n";

/// Filename of the per-store advisory lock. Held exclusively across any
/// read-modify-write of the by-path index so two concurrent writers cannot
/// lose each other's entries.
const LOCK_FILENAME: &str = "lock";

/// Environment variable that points directly at a `.ynotes` directory,
/// bypassing the upward walk (`GIT_DIR` semantics — needed by a future
/// long-lived server that has no meaningful current directory).
const ENV_DIR: &str = "YNOTES_DIR";

/// The reverse index: which note ids belong to each target path.
type IndexMap = std::collections::BTreeMap<String, Vec<String>>;

/// A handle to an opened store, identified by its `.ynotes` directory.
#[derive(Debug, Clone)]
pub struct Store {
    root: PathBuf,
}

impl Store {
    /// Ensures a store exists under `workdir` (i.e. `workdir/.ynotes`).
    /// Idempotent: a pre-existing valid store is reopened, not refused —
    /// "already in the desired state" is success, not an error.
    ///
    /// A `.ynotes` directory that exists but lacks a `HEAD` sentinel is
    /// refused as [`Error::Invalid`] — writing into someone else's directory
    /// of the same name would be unsafe.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if `.ynotes` exists but is not a ynotes
    /// store, or [`Error::Io`] if any directory or sentinel file cannot be
    /// written.
    pub fn init(workdir: &Path) -> Result<Self> {
        let root = workdir.join(STORE_DIRNAME);
        if root.join("HEAD").is_file() {
            return Ok(Self { root });
        }
        if root.exists() {
            return Err(Error::Invalid(format!(
                "`{}` exists but is not a ynotes store (no HEAD)",
                root.display()
            )));
        }
        let store = Self { root };
        mkdir(&store.notes_dir())?;
        mkdir(&store.index_dir())?;
        write_file(&store.head_path(), HEAD_CONTENTS.as_bytes())?;
        store.write_index(&IndexMap::new())?;
        Ok(store)
    }

    /// Opens an existing store given its `.ynotes` directory directly,
    /// validating the `HEAD` sentinel. This is the seam a long-lived server
    /// (which has no meaningful current directory) uses.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if `root` is not a valid store.
    pub fn open(root: &Path) -> Result<Self> {
        if root.join("HEAD").is_file() {
            Ok(Self {
                root: root.to_path_buf(),
            })
        } else {
            Err(Error::Invalid(format!(
                "`{}` is not a ynotes store (no HEAD)",
                root.display()
            )))
        }
    }

    /// Locates the store by walking from `start` up to the filesystem root,
    /// returning the first ancestor containing a `.ynotes/HEAD`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::StoreNotFound`] if no store is found in any ancestor.
    pub fn discover_from(start: &Path) -> Result<Self> {
        let mut dir = start;
        loop {
            let candidate = dir.join(STORE_DIRNAME);
            if candidate.join("HEAD").is_file() {
                return Ok(Self { root: candidate });
            }
            match dir.parent() {
                Some(parent) => dir = parent,
                None => {
                    return Err(Error::StoreNotFound {
                        searched_from: start.to_path_buf(),
                    });
                }
            }
        }
    }

    /// Locates the store: `$YNOTES_DIR` if set (pointed directly at a
    /// `.ynotes` directory), otherwise the nearest ancestor of the current
    /// directory containing a `.ynotes/HEAD`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::StoreNotFound`] if no store is found, [`Error::Io`] if
    /// the current directory cannot be determined, or [`Error::Invalid`] if
    /// `$YNOTES_DIR` does not point at a valid store.
    pub fn discover() -> Result<Self> {
        if let Some(dir) = std::env::var_os(ENV_DIR) {
            return Self::open(&PathBuf::from(dir));
        }
        let start = std::env::current_dir().map_err(|source| Error::Io {
            path: PathBuf::from("."),
            source,
        })?;
        Self::discover_from(&start)
    }

    /// The `.ynotes` directory backing this store.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// The work tree the store sits in (the parent of `.ynotes`).
    ///
    /// # Errors
    ///
    /// [`Error::Invalid`] if `.ynotes` somehow has no parent (e.g. a store
    /// created at a filesystem root).
    pub fn workdir(&self) -> Result<&Path> {
        self.root
            .parent()
            .ok_or_else(|| Error::Invalid("store has no parent directory".to_owned()))
    }

    /// A note's target identity: `path` made relative to the work tree, with
    /// forward slashes. Save and query must agree on this string, so the
    /// derivation collapses anything two spellings of the same physical file
    /// might disagree on — `..` segments, `.` segments, and symlinked roots
    /// like macOS's `/tmp -> /private/tmp` — *before* `strip_prefix`. The
    /// alternative (`std::path::absolute` alone) is purely lexical and treats
    /// `sub/../sub/file.txt` and `sub/file.txt` as different keys, breaking
    /// the content-addressed id invariant (#6) for the same physical file.
    ///
    /// Does **not** require `path` to exist: for a missing input, only the
    /// deepest existing ancestor is canonicalised and the tail is appended
    /// lexically — so `query`/`delete`/`list` can still look up notes whose
    /// target file has since been removed.
    ///
    /// # Errors
    ///
    /// [`Error::OutsideStore`] if `path` resolves outside the work tree
    /// (a user input error the binary maps to exit `2`), or [`Error::Io`] if
    /// the work tree itself cannot be canonicalised.
    pub fn relativize(&self, path: &Path) -> Result<String> {
        let workdir = self.workdir()?;
        let canon_work = workdir.canonicalize().map_err(|source| Error::Io {
            path: workdir.to_path_buf(),
            source,
        })?;
        let canon_path = canonical_for_compare(path);
        match canon_path.strip_prefix(&canon_work) {
            Ok(rel) => Ok(to_forward_slash(rel)),
            Err(_) => Err(Error::OutsideStore {
                path: path.to_path_buf(),
                store_root: canon_work,
            }),
        }
    }

    /// Persists `note`, then indexes it under its target path.
    ///
    /// **Idempotent.** The id is content-addressed, so saving identical
    /// context again is a no-op: the existing record is left untouched.
    /// Returns `true` if this call created a new note, `false` if an
    /// identical one already existed — so an agent retrying a `save` tool
    /// call neither duplicates nor errors.
    ///
    /// **Race-safe.** "Already existed" is detected by an atomic
    /// rename-no-replace, not a check-then-write, so two concurrent saves of
    /// the same content cannot both report `created: true`. Field testing
    /// caught the older TOCTOU form reporting two creations for one record.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if the record or index cannot be written, or
    /// [`Error::Invalid`] if the existing index is unreadable.
    pub fn save(&self, note: &Note) -> Result<bool> {
        let path = self.note_path(&note.id);
        let bytes = serde_json::to_vec_pretty(note)
            .map_err(|e| Error::Invalid(format!("cannot serialise note `{}`: {e}", note.id)))?;
        if let Some(parent) = path.parent() {
            mkdir(parent)?;
        }
        let created = write_file_noclobber(&path, &bytes)?;
        // Always re-touch the index: even when the note already existed, a
        // crash mid-save could have left the file on disk without the index
        // pointer, and `index_note` is idempotent.
        self.index_note(note)?;
        Ok(created)
    }

    /// Saves `note`, then retires every prior note at the *same location* so
    /// only the latest survives — the supersede semantics a content-addressed
    /// store gives editing the body (a new body yields a new id, hence a new
    /// file, which would otherwise coexist with the old one).
    ///
    /// "Same location" is `(target, scope, bundle.position.range)`: re-saving
    /// at one place with changed context replaces what was there; saving at a
    /// *different* range, even on the same file, is an independent note and is
    /// left alone.
    ///
    /// The new note is written **first** (via [`Store::save`]), and only then
    /// are the superseded ones removed, so a crash mid-call leaves the new
    /// note plus possibly some stale siblings — never a hole. This is the
    /// never-silently-dropped invariant applied to supersede.
    ///
    /// Returns `(created, superseded_count)`: `created` is the bool from
    /// [`Store::save`] (`false` when an identical note already existed), and
    /// `superseded_count` is how many prior notes were removed. Re-saving
    /// identical content is therefore `(false, 0)` — the id matches, so
    /// nothing new is written and nothing else sits at that location.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if a record or the index cannot be written or
    /// removed, or [`Error::Invalid`] if the index or a note file is
    /// unreadable.
    pub fn save_superseding(&self, note: &Note) -> Result<(bool, usize)> {
        let created = self.save(note)?;

        let mut superseded = 0;
        for prior in self.notes_for(&note.target)? {
            let same_location = prior.scope == note.scope
                && prior.bundle.position.range == note.bundle.position.range;
            if same_location && prior.id != note.id {
                self.remove(&prior)?;
                superseded += 1;
            }
        }
        Ok((created, superseded))
    }

    /// Adds `note`'s id to the by-path index if absent (idempotent). Runs
    /// under the store's exclusive index lock, so two concurrent saves of
    /// different notes to the same target cannot lose each other's entries.
    fn index_note(&self, note: &Note) -> Result<()> {
        self.with_index_lock(|| {
            let mut index = self.read_index()?;
            let ids = index.entry(note.target.clone()).or_default();
            if !ids.contains(&note.id) {
                ids.push(note.id.clone());
            }
            self.write_index(&index)
        })
    }

    /// Every note whose target is `target` (store-root-relative,
    /// forward-slash). A note id present in the index but missing on disk is
    /// skipped with a warning rather than failing the whole query — the index
    /// is a cache and must not be able to sink a query.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if the index or a present note file is
    /// unreadable as JSON, or [`Error::Io`] on a read failure other than a
    /// missing note file.
    pub fn notes_for(&self, target: &str) -> Result<Vec<Note>> {
        let index = self.read_index()?;
        let Some(ids) = index.get(target) else {
            return Ok(Vec::new());
        };
        let mut notes = Vec::with_capacity(ids.len());
        for id in ids {
            match self.read_note(id) {
                Ok(note) => notes.push(note),
                Err(Error::Io { source, .. }) if source.kind() == std::io::ErrorKind::NotFound => {
                    tracing::warn!(
                        note = %id,
                        "indexed note missing on disk; skipping (run a reindex)"
                    );
                }
                Err(other) => return Err(other),
            }
        }
        Ok(notes)
    }

    /// Every note in the store, in index order.
    ///
    /// # Errors
    ///
    /// As [`Store::notes_for`].
    pub fn all_notes(&self) -> Result<Vec<Note>> {
        let index = self.read_index()?;
        let mut notes = Vec::new();
        for target in index.keys() {
            notes.extend(self.notes_for(target)?);
        }
        Ok(notes)
    }

    /// Every note whose id starts with `prefix` (case-sensitive hex), in
    /// ascending id order. The selection key for `delete` and `update`:
    /// returns 0/1/many so the caller can render the right diagnostic
    /// ("no match", "ambiguous — N candidates", or proceed).
    ///
    /// An index pointer that no longer resolves to a file on disk is skipped
    /// with a `tracing::warn!`, mirroring [`Store::notes_for`]'s posture: a
    /// corrupt index must not be able to sink a lookup.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Invalid`] if the index or a present note record is
    /// unreadable as JSON, or [`Error::Io`] on a read failure other than a
    /// missing note file.
    pub fn find_by_id_prefix(&self, prefix: &str) -> Result<Vec<Note>> {
        let index = self.read_index()?;
        let mut matches = Vec::new();
        for ids in index.values() {
            for id in ids {
                if id.starts_with(prefix) {
                    match self.read_note(id) {
                        Ok(note) => matches.push(note),
                        Err(Error::Io { source, .. })
                            if source.kind() == std::io::ErrorKind::NotFound =>
                        {
                            tracing::warn!(
                                note = %id,
                                "indexed note missing on disk; skipping (run a reindex)"
                            );
                        }
                        Err(other) => return Err(other),
                    }
                }
            }
        }
        matches.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(matches)
    }

    /// Removes a note: de-indexes it, then deletes its record. Used by
    /// `reanchor` to retire the note a refreshed one supersedes. A
    /// already-missing record is not an error (the goal state is reached).
    ///
    /// Runs the index update under the store's exclusive index lock so a
    /// remove cannot race a concurrent save's index write.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Io`] if the index or record cannot be written/removed,
    /// or [`Error::Invalid`] if the index is unreadable.
    pub fn remove(&self, note: &Note) -> Result<()> {
        self.with_index_lock(|| {
            let mut index = self.read_index()?;
            if let Some(ids) = index.get_mut(&note.target) {
                ids.retain(|i| i != &note.id);
                if ids.is_empty() {
                    index.remove(&note.target);
                }
            }
            self.write_index(&index)
        })?;

        let path = self.note_path(&note.id);
        match std::fs::remove_file(&path) {
            Ok(()) => Ok(()),
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(source) => Err(Error::Io { path, source }),
        }
    }

    fn notes_dir(&self) -> PathBuf {
        self.root.join("notes")
    }

    fn index_dir(&self) -> PathBuf {
        self.root.join("index")
    }

    fn index_path(&self) -> PathBuf {
        self.index_dir().join("by-path.json")
    }

    fn head_path(&self) -> PathBuf {
        self.root.join("HEAD")
    }

    /// `notes/<first two hex chars>/<rest>.json`.
    ///
    /// Ids are content-addressed SHA-256, always 64 lowercase hex characters
    /// ([`crate::note::Note::new`] enforces this by construction), so the
    /// split point is unconditional — no need to clamp to `id.len()`.
    fn note_path(&self, id: &str) -> PathBuf {
        let (prefix, rest) = id.split_at(2);
        self.notes_dir().join(prefix).join(format!("{rest}.json"))
    }

    fn read_note(&self, id: &str) -> Result<Note> {
        let path = self.note_path(id);
        let bytes = std::fs::read(&path).map_err(|source| Error::Io {
            path: path.clone(),
            source,
        })?;
        serde_json::from_slice(&bytes).map_err(|e| {
            Error::Invalid(format!("note `{}` is malformed JSON: {e}", path.display()))
        })
    }

    fn read_index(&self) -> Result<IndexMap> {
        let path = self.index_path();
        match std::fs::read(&path) {
            Ok(bytes) => serde_json::from_slice(&bytes).map_err(|e| {
                Error::Invalid(format!("index `{}` is malformed JSON: {e}", path.display()))
            }),
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(IndexMap::new()),
            Err(source) => Err(Error::Io { path, source }),
        }
    }

    fn write_index(&self, index: &IndexMap) -> Result<()> {
        let bytes = serde_json::to_vec_pretty(index)
            .map_err(|e| Error::Invalid(format!("cannot serialise index: {e}")))?;
        write_file(&self.index_path(), &bytes)
    }

    /// Run `f` while holding the store's exclusive advisory lock on
    /// `.ynotes/lock`. The index is a rebuildable cache, but the
    /// read-modify-write that maintains it must be serialised across processes
    /// or two concurrent writers will lose each other's edits.
    ///
    /// The lock is released when the borrowed [`std::fs::File`] is dropped at
    /// the end of this scope, even if `f` panicked; the explicit `unlock`
    /// keeps that release visible at the call site rather than implicit in
    /// drop order.
    fn with_index_lock<R>(&self, f: impl FnOnce() -> Result<R>) -> Result<R> {
        let path = self.root.join(LOCK_FILENAME);
        let file = std::fs::OpenOptions::new()
            .create(true)
            .read(true)
            .write(true)
            .truncate(false)
            .open(&path)
            .map_err(|source| Error::Io {
                path: path.clone(),
                source,
            })?;
        file.lock_exclusive().map_err(|source| Error::Io {
            path: path.clone(),
            source,
        })?;
        let result = f();
        // Best-effort: the OS releases the lock on drop too, so a failure
        // here cannot strand the store; surfacing it would mask the real
        // error from `f`. Named (not `_`) to satisfy `let_underscore_drop`.
        let _unlocked = FileExt::unlock(&file);
        result
    }
}

/// Creates `dir` and all parents, mapping failure to a path-carrying
/// [`Error::Io`].
fn mkdir(dir: &Path) -> Result<()> {
    std::fs::create_dir_all(dir).map_err(|source| Error::Io {
        path: dir.to_path_buf(),
        source,
    })
}

/// Writes `bytes` to `path` atomically: a temp file in the same directory,
/// then a rename. A crash leaves either the old file or the new one, never a
/// truncated mix. Overwrites any existing file
/// at `path` — used for the index and the HEAD sentinel, whose contents
/// must be updated in place.
fn write_file(path: &Path, bytes: &[u8]) -> Result<()> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let io = |source| Error::Io {
        path: path.to_path_buf(),
        source,
    };
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(io)?;
    tmp.write_all(bytes).map_err(io)?;
    tmp.flush().map_err(io)?;
    tmp.persist(path).map_err(|e| Error::Io {
        path: path.to_path_buf(),
        source: e.error,
    })?;
    Ok(())
}

/// Like [`write_file`] but refuses to overwrite — returns `Ok(false)` if
/// `path` already exists, `Ok(true)` on a fresh write.
///
/// The rename-no-replace is atomic (POSIX `link` + `unlink`-on-tmp, Windows
/// `MoveFileExW` without `MOVEFILE_REPLACE_EXISTING`), closing the
/// check-then-write TOCTOU window that previously let two concurrent
/// identical [`Store::save`] calls both report `created: true`. The temp
/// file is dropped (and removed from disk) on the lost-race path.
fn write_file_noclobber(path: &Path, bytes: &[u8]) -> Result<bool> {
    let dir = path.parent().unwrap_or_else(|| Path::new("."));
    let io = |source| Error::Io {
        path: path.to_path_buf(),
        source,
    };
    let mut tmp = tempfile::NamedTempFile::new_in(dir).map_err(io)?;
    tmp.write_all(bytes).map_err(io)?;
    tmp.flush().map_err(io)?;
    match tmp.persist_noclobber(path) {
        Ok(_) => Ok(true),
        Err(e) if e.error.kind() == std::io::ErrorKind::AlreadyExists => Ok(false),
        Err(e) => Err(Error::Io {
            path: path.to_path_buf(),
            source: e.error,
        }),
    }
}
